CREATE TABLE nofronts.user(
	id VARCHAR(36) PRIMARY KEY,
	username VARCHAR(255) UNIQUE NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	name VARCHAR(255) NOT NULL DEFAULT '',
	surname VARCHAR(255) NOT NULL DEFAULT '',
	password VARCHAR(255) NOT NULL
);
