// Code generated by protoc-gen-go. DO NOT EDIT.
// source: profile.proto

package profile

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CurrentUserID struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CurrentUserID) Reset()         { *m = CurrentUserID{} }
func (m *CurrentUserID) String() string { return proto.CompactTextString(m) }
func (*CurrentUserID) ProtoMessage()    {}
func (*CurrentUserID) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0}
}

func (m *CurrentUserID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrentUserID.Unmarshal(m, b)
}
func (m *CurrentUserID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrentUserID.Marshal(b, m, deterministic)
}
func (m *CurrentUserID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrentUserID.Merge(m, src)
}
func (m *CurrentUserID) XXX_Size() int {
	return xxx_messageInfo_CurrentUserID.Size(m)
}
func (m *CurrentUserID) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrentUserID.DiscardUnknown(m)
}

var xxx_messageInfo_CurrentUserID proto.InternalMessageInfo

func (m *CurrentUserID) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type User struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Avatar               string   `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Id                   string   `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UserUpdate struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Avatar               string   `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	NewPassword          string   `protobuf:"bytes,7,opt,name=newPassword,proto3" json:"newPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserUpdate) Reset()         { *m = UserUpdate{} }
func (m *UserUpdate) String() string { return proto.CompactTextString(m) }
func (*UserUpdate) ProtoMessage()    {}
func (*UserUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{2}
}

func (m *UserUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserUpdate.Unmarshal(m, b)
}
func (m *UserUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserUpdate.Marshal(b, m, deterministic)
}
func (m *UserUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserUpdate.Merge(m, src)
}
func (m *UserUpdate) XXX_Size() int {
	return xxx_messageInfo_UserUpdate.Size(m)
}
func (m *UserUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_UserUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_UserUpdate proto.InternalMessageInfo

func (m *UserUpdate) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserUpdate) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserUpdate) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserUpdate) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserUpdate) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserUpdate) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserUpdate) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type UserAvatar struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Avatar               string   `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAvatar) Reset()         { *m = UserAvatar{} }
func (m *UserAvatar) String() string { return proto.CompactTextString(m) }
func (*UserAvatar) ProtoMessage()    {}
func (*UserAvatar) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{3}
}

func (m *UserAvatar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAvatar.Unmarshal(m, b)
}
func (m *UserAvatar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAvatar.Marshal(b, m, deterministic)
}
func (m *UserAvatar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAvatar.Merge(m, src)
}
func (m *UserAvatar) XXX_Size() int {
	return xxx_messageInfo_UserAvatar.Size(m)
}
func (m *UserAvatar) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAvatar.DiscardUnknown(m)
}

var xxx_messageInfo_UserAvatar proto.InternalMessageInfo

func (m *UserAvatar) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserAvatar) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func init() {
	proto.RegisterType((*CurrentUserID)(nil), "profile.CurrentUserID")
	proto.RegisterType((*User)(nil), "profile.User")
	proto.RegisterType((*UserUpdate)(nil), "profile.UserUpdate")
	proto.RegisterType((*UserAvatar)(nil), "profile.UserAvatar")
}

func init() {
	proto.RegisterFile("profile.proto", fileDescriptor_744bf7a47b381504)
}

var fileDescriptor_744bf7a47b381504 = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x92, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x9b, 0xb4, 0x4d, 0xcc, 0xd4, 0x78, 0x58, 0xa5, 0x84, 0x22, 0x58, 0x72, 0xf2, 0x14,
	0xa1, 0xde, 0xf4, 0x62, 0xad, 0x20, 0x5e, 0x44, 0x0a, 0xbd, 0x78, 0x5b, 0xcd, 0x94, 0x06, 0xd3,
	0x24, 0xcc, 0x6e, 0xec, 0x53, 0x79, 0xf5, 0x31, 0x7c, 0x26, 0xd9, 0x3f, 0x69, 0x1b, 0x84, 0x9e,
	0x3d, 0x7e, 0xdf, 0x6f, 0x66, 0xe7, 0x1b, 0x76, 0x20, 0xac, 0xa8, 0x5c, 0x66, 0x39, 0x26, 0x15,
	0x95, 0xb2, 0x64, 0xbe, 0x95, 0xf1, 0x05, 0x84, 0xb3, 0x9a, 0x08, 0x0b, 0xb9, 0x10, 0x48, 0x4f,
	0x0f, 0xec, 0x04, 0xdc, 0x2c, 0x8d, 0x9c, 0xb1, 0x73, 0xd9, 0x9d, 0xbb, 0x59, 0x1a, 0x7f, 0x3b,
	0xd0, 0x53, 0x88, 0x8d, 0xe0, 0xa8, 0x16, 0x48, 0x05, 0x5f, 0xa3, 0xc6, 0xc1, 0x7c, 0xab, 0xd9,
	0x39, 0x04, 0xcb, 0x8c, 0x84, 0x7c, 0x56, 0xd0, 0xd5, 0x70, 0x67, 0xa8, 0xce, 0x9c, 0x5b, 0xd8,
	0x35, 0x9d, 0x8d, 0x56, 0xac, 0xe2, 0x42, 0x6c, 0x4a, 0x4a, 0xa3, 0x9e, 0x61, 0x8d, 0x66, 0x67,
	0xd0, 0xc7, 0x35, 0xcf, 0xf2, 0xa8, 0xaf, 0x81, 0x11, 0x6c, 0x08, 0x1e, 0xff, 0xe4, 0x92, 0x53,
	0xe4, 0x69, 0xdb, 0x2a, 0x1b, 0xdc, 0xd7, 0x9e, 0x0a, 0xfe, 0xe3, 0x00, 0xa8, 0xe0, 0x8b, 0x2a,
	0xe5, 0x12, 0xff, 0x7d, 0xfc, 0x31, 0x0c, 0x0a, 0xdc, 0xbc, 0x34, 0x8f, 0x99, 0x3d, 0xf6, 0xad,
	0xf8, 0xce, 0xec, 0x33, 0x35, 0xf5, 0x87, 0xf6, 0xd9, 0xcd, 0x70, 0xf7, 0x67, 0x4c, 0xbe, 0x1c,
	0x18, 0x4c, 0x6b, 0xb9, 0x9a, 0xad, 0xf0, 0xfd, 0x03, 0x89, 0x4d, 0xc0, 0x57, 0x2f, 0x3e, 0xa2,
	0x64, 0xc3, 0xa4, 0x39, 0x90, 0xd6, 0x39, 0x8c, 0xc2, 0xad, 0xaf, 0x8c, 0xb8, 0xc3, 0x6e, 0x20,
	0x30, 0x09, 0x0e, 0x75, 0x9d, 0xb6, 0xba, 0x4c, 0x7d, 0xdc, 0x61, 0x09, 0x78, 0xf6, 0x37, 0xda,
	0x05, 0xc6, 0xfc, 0x33, 0xeb, 0xfe, 0xf8, 0x15, 0x92, 0xab, 0x5b, 0x6b, 0xbe, 0x79, 0xfa, 0x74,
	0xaf, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x03, 0xd7, 0xf0, 0xcb, 0x02, 0x00, 0x00,
}
