# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: go

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Wait for tests to succeed
      uses: lewagon/wait-on-check-action@master
      with:
        ref: ${{ github.ref }}
        check-name: 'test'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 25

    - name: Wait for lint to succeed
      uses: lewagon/wait-on-check-action@master
      with:
        ref: ${{ github.ref }}
        check-name: 'lint'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 25

    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /root/back/2023_2_Komanda-bez-frontov
          git checkout ${{ secrets.MAIN_BRANCH }}
          git pull
          make kill
          make deploy
