# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" , "dev"]
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install ssh keys
    # check this thread to understand why its needed:
    # https://stackoverflow.com/a/70447517
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: connect and pull
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
        cd ./back/2023_2_Komanda-bez-frontov
        sudo git checkout ${{ secrets.MAIN_BRANCH }}
        sudo git pull
        go test -v ./...
        make kill
        make run
        exit

    - name: cleanup
      run: rm -rf ~/.ssh
