name: test
on:
  push:
    branches:
      - master
      - main
      - dev
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run tests
      run: make test
